name: Create tag/release

on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: string
        default: 'true'

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  build:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.2.0
        if: github.event.inputs.deploy == 'true'
        with:
          concurrent_skipping: 'same_content'
          cancel_others: 'true'

      - name: Check out code
        if: github.event.inputs.deploy == 'true'
        uses: actions/checkout@v2.5.0

      - name: Get current date
        if: github.event.inputs.deploy == 'true'
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT


      - name: Create tag
        if: github.event.inputs.deploy == 'true'
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ secrets.JENKINS_PAT_FLUXCD }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/gha-prod-${{ steps.date.outputs.date }}",
              sha: context.sha
            })

      ##### Git versions #### 
      - name: Check out code
        uses: actions/checkout@v2.5.0
        if: github.event.inputs.deploy == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.JENKINS_PAT_FLUXCD }}
        with:
          fetch-depth: 0
          repository: 'freeletics/releases'
          path: 'releases'
          ref: 'main'
          token: ${{ secrets.JENKINS_PAT_FLUXCD }}


      - name: Create versions.yaml
        uses: mikefarah/yq@v4.30.5
        if: github.event.inputs.deploy == 'false'
        with:
          cmd: yq e '.${{ github.event.repository.name }} = "${{ steps.date.outputs.date }}"' releases/versions.yaml > releases/versions.yaml

      - name: Commit file to versions
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        if: github.event.inputs.deploy == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.JENKINS_PAT_FLUXCD }}
        with:
          commit_message: "${{ github.event.repository.name }} BUMP"
          branch: main
          file_pattern: 'releases/versions.yaml'
          repository: 'releases'
