name: "Run helm tests"

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: false
      AWS_ECR_ENV_NAME:
        required: false
        type: string
        default: "prod"
      AWS_REGION:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      COMMAND:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          concurrent_skipping: "same_content"
          cancel_others: "true"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/github-actions/fl-${{ inputs.AWS_ECR_ENV_NAME }}-${{ github.event.repository.name }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.5.3

      - name: Run ubuntu from dockerhub
        uses: tj-actions/docker-run@v2
        with:
          image: ${{ inputs.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/helm-tests:gha-latest-master
          name: helm-tests
          args: |
            ${{ inputs.COMMAND }}
          options: --workdir=/
