name: "Released"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        if: github.event.inputs.deploy == 'true'
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
      ##### Git versions #### 
      - name: Check out code
        uses: actions/checkout@v3
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        with:
          fetch-depth: 0
          repository: 'freeletics/releases'
          path: 'releases'
          ref: 'main'
          token: ${{ secrets.JENKINS_PAT_FLUXCD }}

      - name: Create versions.yaml
        uses: mikefarah/yq@v4.30.5
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        with:
          cmd: yq e '.${{ github.event.repository.name }} = "${{ steps.date.outputs.date }}"' releases/versions.yaml > releases/versions.yaml

      - name: Push versions.yaml back
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          cd releases
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add versions.yaml
          git commit -m "${{ github.event.repository.name }} BUMP"
          git push