name: "Just a test"

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ["master"]
    tags:
      - "*"

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.9'

      - name: Show environment
        run: |
          env | grep TEST_TOKEN

      - name: Create python script
        run: |
          cat > showenv.py <<'EOF'
          import os

          print(f'Email username is {os.environ.get("TEST_TOKEN", "<unknown")}')
          EOF

      - name: Run python script
        run: |
          python showenv.py
