name: "Web blog Build with Docker Kaniko"

on:
  workflow_call:
    inputs:
      GATSBY_APP_ENV:
        required: false
        type: string
        default: "staging"
      DOCKERFILE:
        required: false
        type: string
        default: "Dockerfile"

permissions:
  id-token: write
  contents: read
  actions: write


jobs:
  build:
    outputs:
      IMAGE_TAG: ${{ steps.IMAGE_TAG.outputs.IMAGE_TAG }}
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          concurrent_skipping: "same_content"
          cancel_others: "true"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache yarn modules
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            public
            .cache
          key: ${{ runner.os }}-${{ inputs.APP_ENV }}-build-web-blog-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.APP_ENV }}-build-web-blog-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Login to NPM 
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Install deps
        run: yarn install --production=false
          
      - name: Build
        run: yarn build
        env:
          NODE_ENV: "production"
          CI: false
          GATSBY_APP_ENV: "${{ inputs.GATSBY_APP_ENV }}"

      - name: Compress Artifacts
        run: |
          cp Docker/sitemap-index-blog.xml public/
          tar -czf public.tar.gz public

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: |
            public.tar.gz
          retention-days: 5

  docker:
    needs: build
    if: contains(github.ref, 'refs/tags/') || contains(github.ref, 'refs/pull/')
    permissions:
      id-token: write
      contents: read
      actions: write
    uses: freeletics/actions/.github/workflows/docker.yaml@main #this has to be public
    with:
      ARTIFACTS_NAME: "public"
      ARTIFACTS_COMPRESSED: true
      DOCKERFILE: "Dockerfile.gha"
      AWS_REGION: "eu-west-1"
      AWS_ACCOUNT_ID: "524690225562"
    secrets: inherit

  integration:
    if: contains(github.ref, 'refs/heads/')
    needs: build
    permissions:
      id-token: write
      contents: read
      actions: write
    uses: freeletics/actions/.github/workflows/gha-auto-deploy-integration.yaml@main
    with:
      ARTIFACTS_NAME: "public"
      ARTIFACTS_COMPRESSED: true
      DOCKERFILE: "Dockerfile.gha"
      AWS_REGION: "eu-west-1"
      AWS_ACCOUNT_ID: "524690225562"
    secrets: inherit
